### PR TITLE
Add taskgraph skeleton.

### PR DESCRIPTION
**Pull request by tomprince**

### CODE REVIEW

**Comment by tomprince** [comment]
@Callek

**Review by Callek — COMMENTED** [review]
Offhand this looks good, I'd want an r+ from Pike just to be sure we don't break his workflow before we have this fully setup.  I didn't mentally try to eval the json-e for taskcluster.yml but nothing stood out as wrong.

**Review by Pike — COMMENTED** [review]
So, the `Dockerfile` worksforme. The docker image is slightly bigger, but that could also just be updates to the base distro.

I have to admit that the rest is just confusing to me.

One thing I noticed is that it uses `pytest`, which I, personally, avoid like the plague.

**Review by Pike — APPROVED** [review]
We talked about this some more on slack, r=me.

**Pull request merged**
