### PR TITLE
Format code with black.

### PR DESCRIPTION
**Pull request by tomprince**

### CODE REVIEW

**Comment by Pike** [comment]
Sorry, but I don't like my code going through black at all.

**Comment by tomprince** [comment]
> Sorry, but I don't like my code going through black at all.

Can you expand on why? My impression is that the python community is moving towards adopting it, generally. And mozilla-central in particular is planning to adopt it; as is releng.

I definitely don't like all of its choices, but having a tool care about formatting is much nicer than needing to do it by hand.

**Comment by Pike** [comment]
My take is this:

There's costs on either side, and the size of those costs vary by how people's brains work.

For me, the cost of making formatting decisions is very low.

OTH, that some program does changes to my code that may or may not conflict with my intent on how to convey the patterns and principles of an algorithm to another human (even my future me) ... that's really stressful to me.

It's really about what's stressful to me. And how many folks I'm asked to compromise with.

**Comment by Pike** [comment]
We talked about this a while back, and decided to leave the code w/out black for now.

**Pull request closed without merging**
